### PR TITLE
fix: when using ssl_enabled to determine whether NGX_SSL is defined

### PR DESCRIPTION
**Pull request by rainingmaster**

### CODE REVIEW

**Comment by zhangp8x** [comment]
@rainingmaster 
Thank you for your MR, the sign-off-by is required. Your contribution will be discussed and will give you feedback asap.

The commit message in the pull request does not contain "Signed-off-by:" in it adhering to license and Developer Certification of Origin.
Could you please update the pull request commit message with "Signed-off-by:" in the following format
Signed-off-by: Name
Note: You are required to use your real name in the sign-off message.

**Comment by rainingmaster** [comment]
@zhangp8x

Hi, Thanks for reply, I have finish the sign-off

**Comment by zhangp8x** [comment]
@rainingmaster 

What issue does this patch fixed? Could you please add more information?

**Comment by rainingmaster** [comment]
@zhangp8x 

Hi, sorry for my delay. When I run `./configure && make` under this repo(in fact I forgot add `--with-stream_ssl_module` or `--with-http_ssl_module`), we will get an error: `error: no member named 'ssl_enabled' in 'struct ngx_connection_s'`.

As I investigate, this repo should support build without `NGX_SSL`, such as [this change](https://github.com/intel/asynch_mode_nginx/blob/master/src/event/modules/ngx_epoll_module.c#L127), so I think we should keep the code style always.

**Comment by zhangp8x** [comment]
@rainingmaster 

Your PR would be released in next release. Thank you for your support.

**Pull request closed without merging**
