### PR TITLE
bugfix: nginx crashes when enable thread pool.

### PR DESCRIPTION
**Pull request by zhuizhuhaomeng**
Signed-off-by: lijunlong <lijunlong@openresty.com>

### CODE REVIEW

**Comment by WalterRan** [comment]
Thank you for your PR.
Would you please provide more detail information about how to reproduce this issue?
And we'll test internally.

**Comment by zhuizhuhaomeng** [comment]
I did not provide the signed-off in the old PR. Please goto  https://github.com/intel/asynch_mode_nginx/pull/52 for more detail.

**Comment by WalterRan** [comment]
Thanks for your contribution, the patch will be tested internally and included in the next release.

**Comment by mapicccy** [comment]
I have also met this issue. And I fixed this problem just exactly as the author does

The nginx config file is nginx-ori.conf, the content:
```
thread_pool dlb threads=16 max_queue=65535;
http {
    aio threads=dlb;
    xxx;
}
```

Start the nginx: nginx -p `pwd` -c nginx-ori.conf
Start the benchmark:
```
k6 run -u 32 script.js
```
And the content of the script.js:
```
import http from 'k6/http';
import { check, sleep } from 'k6';

export let options = {
	insecureSkipTLSVerify: true,
	noConnectionReuse: true,
	noVUConnectionReuse: true,

	duration: '20s',
};

export default function () {
	const res = http.get('https://localhost:9001/', {headers: {"Accept-Encoding": "gzip"}});
	check(res, { 'status was 200': (r) => r.status == 200 });
}
```

Debug nginx:
image

**Pull request closed without merging**
