### PR TITLE
修复keepalive模式下，large header的处理错误

### PR DESCRIPTION
**Pull request by jiangzhuti**
此处应该是遗漏了hc->nbusy=0

### CODE REVIEW

**Comment by daweiq** [comment]
非常感谢你的patch，请问你是如何触发keep alive下large header错误的？

**Comment by jiangzhuti** [comment]
> 非常感谢你的patch，请问你是如何触发keep alive下large header错误的？

keepalive模式，每次请求附带长header，到第五次请求返回400错误码

**Comment by daweiq** [comment]
好的，我们会先验证一下patch，然后再进一步处理。

**Comment by jiangzhuti** [comment]
> 好的，我们会先验证一下patch，然后再进一步处理。
用的是默认配置
http://nginx.org/en/docs/http/ngx_http_core_module.html#client_header_buffer_size

**Comment by zhangp8x** [comment]
@jiangzhuti:
Sincere apologies for very late reply to this pull request.
We intend to merge this pull request which will go through the internal process and should be available in the next release. But before that the commit message in the pull request does not contain "Signed-off-by:" in it adhering to license and Developer Certification of Origin.
Could you please update the pull request commit message with "Signed-off-by:" in the following format
Signed-off-by: Name <Email>

Note: You are required to use your real name in the sign-off message.

**Comment by zhangp8x** [comment]
@jiangzhuti 
Do not forget to provide your email at the same time.

**Comment by jiangzhuti** [comment]
@zhangp8x commit message updated, is this okay?

**Comment by daweiq** [comment]
@jiangzhuti The changes are done and merged in the internal branch. It should be available in Github with the next release. Thanks for your contribution!

**Comment by daweiq** [comment]
Patch included in v0.3.9 release, thank you for contribution!

**Pull request closed without merging**
